settings:
  files:
    outputs:
      status: false
      path: ""
      name: .r.outputs.log
    logs:
      status: false
      path: ""
      name: .r.logs.log
    errors:
      status: false
      path: ""
      name: .r.errors.log
  legacy:
    force: true
    interval: 0ms
schema:
  - name: OAuth Server
    path: .
    env:
      ENV: "dev"
      SERVICE_NAME: "oauth-service"



      PORT: "5003"
      APP_URL: "localhost"
      WETIX_SECRET: "tVbo5qN7iht8QBCKsjungvg8uUkbRWxI"

      WETIX_SESSION_ID: "wetix.sb.sid"
      WETIX_COOKIE_DOMAIN: ".wetix.my"

      WETIX_OAUTH_ORIGIN: "http://sb-oauth2.wetix.my"
      WETIX_WEBSITE_ORIGIN: "http://sb.wetix.my"
      WETIX_API_ORIGIN: "https://sb-api.wetix.my"
      WETIX_OPEN_API_ORIGIN: "https://sb-open.wetix.my"
      WETIX_OPEN_GRAPH_ORIGIN: "https://sb-open.wetix.my/graphql"
      WETIX_INTERNAL_GRAPH_ORIGIN: "http://localhost:5500"

      # MySQL
      WETIX_MYSQL_HOST: "rm-zf8wjdf9rnvk703yv6o.mysql.kualalumpur.rds.aliyuncs.com"
      WETIX_MYSQL_PORT: "3306"
      WETIX_MYSQL_USERNAME: "wetix_admin"
      WETIX_MYSQL_PASSWORD: "aSQo5WjCrfGLWHj9lC6JVnRWuVibCpLo"
      WETIX_MYSQL_DATABASE: "wetix-sandbox"

      SSL_CERT: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMrakNDQWVLZ0F3SUJBZ0lSQVBOdDBmRERoUEJheXZSOXQyN2pvWTh3RFFZSktvWklodmNOQVFFTEJRQXcKRWpFUU1BNEdBMVVFQ2hNSFFXTnRaU0JEYnpBZUZ3MHlNVEF5TWpjd01qTTVNRFphRncweU1qQXlNamN3TWpNNQpNRFphTUJJeEVEQU9CZ05WQkFvVEIwRmpiV1VnUTI4d2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3CmdnRUtBb0lCQVFEb2crMVh4cVRMM1QzcHRRWFlkcy9MYS9BYlFNNUxNdy9JeWRBMHpkVGI2bTRUQ3Y4SmpHZDgKNkNtWm04UkxVd1J0OUtaSEVGYjlybjB2Z29PVjRzUHJUb2xxZFN5QVI1WSt2R3F0UWN1dmlnNU5rbWNMYy8yaQpNa0JHT2MrZXVrMDF1K1FnbnJhTTlLQUxHaXhpVG5oL3Ezd3B3SHNEOVNncTVMZTlsMEpnVHpGZ016OTQ0ZUlyCmVGODJWU0hKUitpcmJjelVmZXR5ek5IU1hkMit2V2VpMFp5NHQyTGFIVk9oUFY5SFRCU2I2RmFZdUdGY2VwSWUKUVRORU1WeVdtc1ZMRGRiYzZmSkJoYmY2WXdTakU4a2c1V21YZzVhMUFMV014RmFVSURrQUQxbC96L1hTdTJXNwpKdU9BVG1PbTVmMkFIcmJINExWb3BQV1FJS0gvZXNzQkFnTUJBQUdqU3pCSk1BNEdBMVVkRHdFQi93UUVBd0lGCm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBVEFNQmdOVkhSTUJBZjhFQWpBQU1CUUdBMVVkRVFRTk1BdUMKQ1d4dlkyRnNhRzl6ZERBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQTNQSkMzNmswcjZmV1FITEVBTHBjQVBYOAovbFZ1WG8rN2duRmRKUFlRNGtYbEtSTDRlT1EzU0hYT2lhR1d1blVVNWZUWTQ5a3FpQjdaUEVUQldmYnA0Z3lKCjhlMUZlSlRHdEp1akFaWnJPQnlGMjFUVFZUTEJFMC9iQit4YkNEcktpa01pdWtkMWxGRGxTUHRoRFN5SjBzZkgKTitzTWN6KzdZVEhweHJtNmNLV2xoMFpqZHBKZzFjQkpYMEtmamYwaVNRKzROMlFLdEtzZ1NCanBtOGVoNXpxQgo1OWM3OTQwcmRaWVFIWGtreHl5UXJlbll3Yi9KSFYwUGV0aU5FK1BqOWd1Sjl3TWY1Z2JKTjFUcHZGV09kWGFwCmVodW1naVFQQmdPWGlaWHFVZkQwT1lVVWFEYm1ZbFhlb2RpOWRyTk9uY3VQVnVYNjUwb2kycEpHU0RsRTh3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ=="
      SSL_KEY: "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRRG9nKzFYeHFUTDNUM3AKdFFYWWRzL0xhL0FiUU01TE13L0l5ZEEwemRUYjZtNFRDdjhKakdkODZDbVptOFJMVXdSdDlLWkhFRmI5cm4wdgpnb09WNHNQclRvbHFkU3lBUjVZK3ZHcXRRY3V2aWc1TmttY0xjLzJpTWtCR09jK2V1azAxdStRZ25yYU05S0FMCkdpeGlUbmgvcTN3cHdIc0Q5U2dxNUxlOWwwSmdUekZnTXo5NDRlSXJlRjgyVlNISlIraXJiY3pVZmV0eXpOSFMKWGQyK3ZXZWkwWnk0dDJMYUhWT2hQVjlIVEJTYjZGYVl1R0ZjZXBJZVFUTkVNVnlXbXNWTERkYmM2ZkpCaGJmNgpZd1NqRThrZzVXbVhnNWExQUxXTXhGYVVJRGtBRDFsL3ovWFN1Mlc3SnVPQVRtT201ZjJBSHJiSDRMVm9wUFdRCklLSC9lc3NCQWdNQkFBRUNnZ0VBYktuYkxmNWozZktUa0xsTTloRHdvN3phQmFLUHhvMGlmMC94d2Z1LzB0Y0kKZ2xYTlF3VWZDRHpuMUNYNzRzZjFkZjIwQjlvWERZK1NhYld4RVVkZEVJY3ZxVlVCYXlJSmtXQTA2cXVwS1d4Mwpxc0VVNzBGUjg0OVFnb0ZhQ25BK3pUSDJOMWgxTUFMVEdOMHVpUExyVlo4cTg4aEV0V0RKV09KekRHTzRYWkZBCi9lRmc4L3RPNUFpRHVwVlR2blV2bEhyb25yMG4zY21vbkZtb21wVFBRTnJPczgvc3JreW5NWGhjMU95R1NwbVQKbUc0TW91c0pqWGpVRmlDTHdoUEhNT1pEUjY4U29XTHBER1RScWJkd2lrb3VIaTFSTnpHOGY4MzE4c2YybWZ6TAp4bXFESVdGUzhndVEyd3V1b09uRDdJbWRkOWJnOU5TdGdYRHhHV3duQVFLQmdRRDZzRk53VVZ4eDAyaDhkMWNaCndzZFpJYmNZMC9YZFo1ZmRrK0FrbHZNV2NsaEJhMUEwT2N4VXFDbXVNUk1mNCtqTXhBYjEzTC83eTVqYWFFL2cKUGRwdzFPNEowWDIvVVJQZjhyaDVsbHBTeFJHMEswVW9oTVlQMjlHT2lVRTRBVXFvVG9XZnZoOGlRMXU2ejhHWgovdXpHRDNTSmlWYk1OdTFjRld3V0xqMGptUUtCZ1FEdGNRaHd5eldUWTBScFkrQ1hKK1Q2VDN3NEJGeUpRVUdKCjE1QmZCRTQ2OFROaVZiMU5kM3VsQk9xRUV4b1I2ZGs5SGlIeXNoMmxoK1d2T2V5QXhYc1VJVGw1OGpwRGM1ZGUKaWQrMzlveUNSNjFqK2RiYnovdWdzbDJOb01WUXdFbEdSMmQ2TUlZSER4ZXA5SHQwaDVLOGEwMXk4TjZ4QjBiRwpoNmd3SDMrRHFRS0JnUUR2VzlLZmFKLzY4dDlPRUdpeTZSNk1SVHZjMGUxc3RFLzF1ZzhIQUxZa0ZaT2RDd2p1CmhNMUxlN0VvYUNVWml2UXFKM1Y1NVlmTnRHMURCTnhYZ05lRWFscktOeU40dThKZFR4VEN5ME44eWp1SUt0U0MKeHB1U1l0R281ZmJHc2IwR0RNdGJaaDIyQ2xpWWUyd2dUSjdvMGJMMDY1UmJzb3BhSlA0cUE0Wk82UUtCZ0EzVApUeEtDUXBSYWExbFhuM1F0dG45OHNWYnhxaEd6NHdVTHNEUllJOVg2eFdzc1l1Rm4yNk00TGcrU3JTbnQyK0JiCktNN2c0Q2tMU0t4elN2b1VoWjRlY1NKUW9HUGREeXRLQytUQ1Rsd25vRWo1K3pEQlkzMXY1VktoMGR0cDF0cG8KdmZXM2JaWnJvbzBhMXpWcHozbDVKZ0ZUVlNRcHNFMVBDTlFFZ1lCQkFvR0FYQ0ZudHQ3YW1NY1IyL2VsTFdPMgpOSWp2WVg0VjhYaFRwUVhJeWgxYnRkazg2cUJ2Y2YxdC9QRzhDSHBwaUtGWHB1REN4WHNUN081dEc0NWdZazFVCnlFZGlIWlJXNEJVQ1BUcWQrYytFU3QyVElIQ2tZU3gwSGNFM0xNYkVPVEt1U0hoY1daUWdJeXJUWWxYeHhXcVoKM0lzdXMwRFRKOTE4NENHeHkwS1ZwV2M9Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0="
    commands:
      install:
        status: true
        method: go install
      run:
        status: true
    watcher:
      scripts:
        - type: before
          command: go generate
          global: true
          output: true
        - type: before
          command: make pb
          global: true
          output: true
      extensions:
        - go
      paths:
        - /
      ignored_paths:
        - .git
        - .realize
        - vendor
